package proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: livro.proto

public final class LivroOuterClass {
  private LivroOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LivroOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Livro)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>required string titulo = 2;</code>
     * @return Whether the titulo field is set.
     */
    boolean hasTitulo();
    /**
     * <code>required string titulo = 2;</code>
     * @return The titulo.
     */
    java.lang.String getTitulo();
    /**
     * <code>required string titulo = 2;</code>
     * @return The bytes for titulo.
     */
    com.google.protobuf.ByteString
        getTituloBytes();

    /**
     * <code>required string autor = 3;</code>
     * @return Whether the autor field is set.
     */
    boolean hasAutor();
    /**
     * <code>required string autor = 3;</code>
     * @return The autor.
     */
    java.lang.String getAutor();
    /**
     * <code>required string autor = 3;</code>
     * @return The bytes for autor.
     */
    com.google.protobuf.ByteString
        getAutorBytes();

    /**
     * <code>required int32 ano = 4;</code>
     * @return Whether the ano field is set.
     */
    boolean hasAno();
    /**
     * <code>required int32 ano = 4;</code>
     * @return The ano.
     */
    int getAno();

    /**
     * <code>required string editora = 5;</code>
     * @return Whether the editora field is set.
     */
    boolean hasEditora();
    /**
     * <code>required string editora = 5;</code>
     * @return The editora.
     */
    java.lang.String getEditora();
    /**
     * <code>required string editora = 5;</code>
     * @return The bytes for editora.
     */
    com.google.protobuf.ByteString
        getEditoraBytes();

    /**
     * <code>required string genero = 6;</code>
     * @return Whether the genero field is set.
     */
    boolean hasGenero();
    /**
     * <code>required string genero = 6;</code>
     * @return The genero.
     */
    java.lang.String getGenero();
    /**
     * <code>required string genero = 6;</code>
     * @return The bytes for genero.
     */
    com.google.protobuf.ByteString
        getGeneroBytes();
  }
  /**
   * Protobuf type {@code Livro}
   */
  public  static final class Livro extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Livro)
      LivroOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Livro.newBuilder() to construct.
    private Livro(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Livro() {
      titulo_ = "";
      autor_ = "";
      editora_ = "";
      genero_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Livro();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Livro(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              titulo_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              autor_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              ano_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              editora_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              genero_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LivroOuterClass.internal_static_Livro_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LivroOuterClass.internal_static_Livro_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LivroOuterClass.Livro.class, LivroOuterClass.Livro.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int TITULO_FIELD_NUMBER = 2;
    private volatile java.lang.Object titulo_;
    /**
     * <code>required string titulo = 2;</code>
     * @return Whether the titulo field is set.
     */
    public boolean hasTitulo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string titulo = 2;</code>
     * @return The titulo.
     */
    public java.lang.String getTitulo() {
      java.lang.Object ref = titulo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          titulo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string titulo = 2;</code>
     * @return The bytes for titulo.
     */
    public com.google.protobuf.ByteString
        getTituloBytes() {
      java.lang.Object ref = titulo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        titulo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTOR_FIELD_NUMBER = 3;
    private volatile java.lang.Object autor_;
    /**
     * <code>required string autor = 3;</code>
     * @return Whether the autor field is set.
     */
    public boolean hasAutor() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string autor = 3;</code>
     * @return The autor.
     */
    public java.lang.String getAutor() {
      java.lang.Object ref = autor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          autor_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string autor = 3;</code>
     * @return The bytes for autor.
     */
    public com.google.protobuf.ByteString
        getAutorBytes() {
      java.lang.Object ref = autor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        autor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANO_FIELD_NUMBER = 4;
    private int ano_;
    /**
     * <code>required int32 ano = 4;</code>
     * @return Whether the ano field is set.
     */
    public boolean hasAno() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required int32 ano = 4;</code>
     * @return The ano.
     */
    public int getAno() {
      return ano_;
    }

    public static final int EDITORA_FIELD_NUMBER = 5;
    private volatile java.lang.Object editora_;
    /**
     * <code>required string editora = 5;</code>
     * @return Whether the editora field is set.
     */
    public boolean hasEditora() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required string editora = 5;</code>
     * @return The editora.
     */
    public java.lang.String getEditora() {
      java.lang.Object ref = editora_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          editora_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string editora = 5;</code>
     * @return The bytes for editora.
     */
    public com.google.protobuf.ByteString
        getEditoraBytes() {
      java.lang.Object ref = editora_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        editora_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENERO_FIELD_NUMBER = 6;
    private volatile java.lang.Object genero_;
    /**
     * <code>required string genero = 6;</code>
     * @return Whether the genero field is set.
     */
    public boolean hasGenero() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required string genero = 6;</code>
     * @return The genero.
     */
    public java.lang.String getGenero() {
      java.lang.Object ref = genero_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          genero_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string genero = 6;</code>
     * @return The bytes for genero.
     */
    public com.google.protobuf.ByteString
        getGeneroBytes() {
      java.lang.Object ref = genero_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        genero_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTitulo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAutor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAno()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEditora()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGenero()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, titulo_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, autor_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, ano_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, editora_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, genero_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, titulo_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, autor_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, ano_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, editora_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, genero_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LivroOuterClass.Livro)) {
        return super.equals(obj);
      }
      LivroOuterClass.Livro other = (LivroOuterClass.Livro) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasTitulo() != other.hasTitulo()) return false;
      if (hasTitulo()) {
        if (!getTitulo()
            .equals(other.getTitulo())) return false;
      }
      if (hasAutor() != other.hasAutor()) return false;
      if (hasAutor()) {
        if (!getAutor()
            .equals(other.getAutor())) return false;
      }
      if (hasAno() != other.hasAno()) return false;
      if (hasAno()) {
        if (getAno()
            != other.getAno()) return false;
      }
      if (hasEditora() != other.hasEditora()) return false;
      if (hasEditora()) {
        if (!getEditora()
            .equals(other.getEditora())) return false;
      }
      if (hasGenero() != other.hasGenero()) return false;
      if (hasGenero()) {
        if (!getGenero()
            .equals(other.getGenero())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasTitulo()) {
        hash = (37 * hash) + TITULO_FIELD_NUMBER;
        hash = (53 * hash) + getTitulo().hashCode();
      }
      if (hasAutor()) {
        hash = (37 * hash) + AUTOR_FIELD_NUMBER;
        hash = (53 * hash) + getAutor().hashCode();
      }
      if (hasAno()) {
        hash = (37 * hash) + ANO_FIELD_NUMBER;
        hash = (53 * hash) + getAno();
      }
      if (hasEditora()) {
        hash = (37 * hash) + EDITORA_FIELD_NUMBER;
        hash = (53 * hash) + getEditora().hashCode();
      }
      if (hasGenero()) {
        hash = (37 * hash) + GENERO_FIELD_NUMBER;
        hash = (53 * hash) + getGenero().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LivroOuterClass.Livro parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LivroOuterClass.Livro parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LivroOuterClass.Livro parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LivroOuterClass.Livro parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LivroOuterClass.Livro parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LivroOuterClass.Livro parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LivroOuterClass.Livro parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LivroOuterClass.Livro parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LivroOuterClass.Livro parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LivroOuterClass.Livro parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LivroOuterClass.Livro parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LivroOuterClass.Livro parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LivroOuterClass.Livro prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Livro}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Livro)
        LivroOuterClass.LivroOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LivroOuterClass.internal_static_Livro_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LivroOuterClass.internal_static_Livro_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LivroOuterClass.Livro.class, LivroOuterClass.Livro.Builder.class);
      }

      // Construct using LivroOuterClass.Livro.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        titulo_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        autor_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        ano_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        editora_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        genero_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LivroOuterClass.internal_static_Livro_descriptor;
      }

      @java.lang.Override
      public LivroOuterClass.Livro getDefaultInstanceForType() {
        return LivroOuterClass.Livro.getDefaultInstance();
      }

      @java.lang.Override
      public LivroOuterClass.Livro build() {
        LivroOuterClass.Livro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public LivroOuterClass.Livro buildPartial() {
        LivroOuterClass.Livro result = new LivroOuterClass.Livro(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.titulo_ = titulo_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.autor_ = autor_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.ano_ = ano_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.editora_ = editora_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.genero_ = genero_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LivroOuterClass.Livro) {
          return mergeFrom((LivroOuterClass.Livro)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LivroOuterClass.Livro other) {
        if (other == LivroOuterClass.Livro.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTitulo()) {
          bitField0_ |= 0x00000002;
          titulo_ = other.titulo_;
          onChanged();
        }
        if (other.hasAutor()) {
          bitField0_ |= 0x00000004;
          autor_ = other.autor_;
          onChanged();
        }
        if (other.hasAno()) {
          setAno(other.getAno());
        }
        if (other.hasEditora()) {
          bitField0_ |= 0x00000010;
          editora_ = other.editora_;
          onChanged();
        }
        if (other.hasGenero()) {
          bitField0_ |= 0x00000020;
          genero_ = other.genero_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasTitulo()) {
          return false;
        }
        if (!hasAutor()) {
          return false;
        }
        if (!hasAno()) {
          return false;
        }
        if (!hasEditora()) {
          return false;
        }
        if (!hasGenero()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LivroOuterClass.Livro parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LivroOuterClass.Livro) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       * @return Whether the id field is set.
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object titulo_ = "";
      /**
       * <code>required string titulo = 2;</code>
       * @return Whether the titulo field is set.
       */
      public boolean hasTitulo() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string titulo = 2;</code>
       * @return The titulo.
       */
      public java.lang.String getTitulo() {
        java.lang.Object ref = titulo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            titulo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string titulo = 2;</code>
       * @return The bytes for titulo.
       */
      public com.google.protobuf.ByteString
          getTituloBytes() {
        java.lang.Object ref = titulo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          titulo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string titulo = 2;</code>
       * @param value The titulo to set.
       * @return This builder for chaining.
       */
      public Builder setTitulo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        titulo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string titulo = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitulo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        titulo_ = getDefaultInstance().getTitulo();
        onChanged();
        return this;
      }
      /**
       * <code>required string titulo = 2;</code>
       * @param value The bytes for titulo to set.
       * @return This builder for chaining.
       */
      public Builder setTituloBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        titulo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object autor_ = "";
      /**
       * <code>required string autor = 3;</code>
       * @return Whether the autor field is set.
       */
      public boolean hasAutor() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string autor = 3;</code>
       * @return The autor.
       */
      public java.lang.String getAutor() {
        java.lang.Object ref = autor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            autor_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string autor = 3;</code>
       * @return The bytes for autor.
       */
      public com.google.protobuf.ByteString
          getAutorBytes() {
        java.lang.Object ref = autor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          autor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string autor = 3;</code>
       * @param value The autor to set.
       * @return This builder for chaining.
       */
      public Builder setAutor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        autor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string autor = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAutor() {
        bitField0_ = (bitField0_ & ~0x00000004);
        autor_ = getDefaultInstance().getAutor();
        onChanged();
        return this;
      }
      /**
       * <code>required string autor = 3;</code>
       * @param value The bytes for autor to set.
       * @return This builder for chaining.
       */
      public Builder setAutorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        autor_ = value;
        onChanged();
        return this;
      }

      private int ano_ ;
      /**
       * <code>required int32 ano = 4;</code>
       * @return Whether the ano field is set.
       */
      public boolean hasAno() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required int32 ano = 4;</code>
       * @return The ano.
       */
      public int getAno() {
        return ano_;
      }
      /**
       * <code>required int32 ano = 4;</code>
       * @param value The ano to set.
       * @return This builder for chaining.
       */
      public Builder setAno(int value) {
        bitField0_ |= 0x00000008;
        ano_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ano = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAno() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ano_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object editora_ = "";
      /**
       * <code>required string editora = 5;</code>
       * @return Whether the editora field is set.
       */
      public boolean hasEditora() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required string editora = 5;</code>
       * @return The editora.
       */
      public java.lang.String getEditora() {
        java.lang.Object ref = editora_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            editora_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string editora = 5;</code>
       * @return The bytes for editora.
       */
      public com.google.protobuf.ByteString
          getEditoraBytes() {
        java.lang.Object ref = editora_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          editora_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string editora = 5;</code>
       * @param value The editora to set.
       * @return This builder for chaining.
       */
      public Builder setEditora(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        editora_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string editora = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearEditora() {
        bitField0_ = (bitField0_ & ~0x00000010);
        editora_ = getDefaultInstance().getEditora();
        onChanged();
        return this;
      }
      /**
       * <code>required string editora = 5;</code>
       * @param value The bytes for editora to set.
       * @return This builder for chaining.
       */
      public Builder setEditoraBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        editora_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object genero_ = "";
      /**
       * <code>required string genero = 6;</code>
       * @return Whether the genero field is set.
       */
      public boolean hasGenero() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required string genero = 6;</code>
       * @return The genero.
       */
      public java.lang.String getGenero() {
        java.lang.Object ref = genero_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            genero_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string genero = 6;</code>
       * @return The bytes for genero.
       */
      public com.google.protobuf.ByteString
          getGeneroBytes() {
        java.lang.Object ref = genero_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          genero_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string genero = 6;</code>
       * @param value The genero to set.
       * @return This builder for chaining.
       */
      public Builder setGenero(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        genero_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string genero = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearGenero() {
        bitField0_ = (bitField0_ & ~0x00000020);
        genero_ = getDefaultInstance().getGenero();
        onChanged();
        return this;
      }
      /**
       * <code>required string genero = 6;</code>
       * @param value The bytes for genero to set.
       * @return This builder for chaining.
       */
      public Builder setGeneroBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        genero_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Livro)
    }

    // @@protoc_insertion_point(class_scope:Livro)
    private static final LivroOuterClass.Livro DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LivroOuterClass.Livro();
    }

    public static LivroOuterClass.Livro getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Livro>
        PARSER = new com.google.protobuf.AbstractParser<Livro>() {
      @java.lang.Override
      public Livro parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Livro(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Livro> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Livro> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public LivroOuterClass.Livro getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LivrosOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Livros)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Livro livros = 1;</code>
     */
    java.util.List<LivroOuterClass.Livro> 
        getLivrosList();
    /**
     * <code>repeated .Livro livros = 1;</code>
     */
    LivroOuterClass.Livro getLivros(int index);
    /**
     * <code>repeated .Livro livros = 1;</code>
     */
    int getLivrosCount();
    /**
     * <code>repeated .Livro livros = 1;</code>
     */
    java.util.List<? extends LivroOuterClass.LivroOrBuilder> 
        getLivrosOrBuilderList();
    /**
     * <code>repeated .Livro livros = 1;</code>
     */
    LivroOuterClass.LivroOrBuilder getLivrosOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Livros}
   */
  public  static final class Livros extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Livros)
      LivrosOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Livros.newBuilder() to construct.
    private Livros(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Livros() {
      livros_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Livros();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Livros(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                livros_ = new java.util.ArrayList<LivroOuterClass.Livro>();
                mutable_bitField0_ |= 0x00000001;
              }
              livros_.add(
                  input.readMessage(LivroOuterClass.Livro.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          livros_ = java.util.Collections.unmodifiableList(livros_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LivroOuterClass.internal_static_Livros_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LivroOuterClass.internal_static_Livros_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LivroOuterClass.Livros.class, LivroOuterClass.Livros.Builder.class);
    }

    public static final int LIVROS_FIELD_NUMBER = 1;
    private java.util.List<LivroOuterClass.Livro> livros_;
    /**
     * <code>repeated .Livro livros = 1;</code>
     */
    public java.util.List<LivroOuterClass.Livro> getLivrosList() {
      return livros_;
    }
    /**
     * <code>repeated .Livro livros = 1;</code>
     */
    public java.util.List<? extends LivroOuterClass.LivroOrBuilder> 
        getLivrosOrBuilderList() {
      return livros_;
    }
    /**
     * <code>repeated .Livro livros = 1;</code>
     */
    public int getLivrosCount() {
      return livros_.size();
    }
    /**
     * <code>repeated .Livro livros = 1;</code>
     */
    public LivroOuterClass.Livro getLivros(int index) {
      return livros_.get(index);
    }
    /**
     * <code>repeated .Livro livros = 1;</code>
     */
    public LivroOuterClass.LivroOrBuilder getLivrosOrBuilder(
        int index) {
      return livros_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getLivrosCount(); i++) {
        if (!getLivros(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < livros_.size(); i++) {
        output.writeMessage(1, livros_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < livros_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, livros_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LivroOuterClass.Livros)) {
        return super.equals(obj);
      }
      LivroOuterClass.Livros other = (LivroOuterClass.Livros) obj;

      if (!getLivrosList()
          .equals(other.getLivrosList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getLivrosCount() > 0) {
        hash = (37 * hash) + LIVROS_FIELD_NUMBER;
        hash = (53 * hash) + getLivrosList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LivroOuterClass.Livros parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LivroOuterClass.Livros parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LivroOuterClass.Livros parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LivroOuterClass.Livros parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LivroOuterClass.Livros parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LivroOuterClass.Livros parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LivroOuterClass.Livros parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LivroOuterClass.Livros parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LivroOuterClass.Livros parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LivroOuterClass.Livros parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LivroOuterClass.Livros parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LivroOuterClass.Livros parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LivroOuterClass.Livros prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Livros}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Livros)
        LivroOuterClass.LivrosOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LivroOuterClass.internal_static_Livros_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LivroOuterClass.internal_static_Livros_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LivroOuterClass.Livros.class, LivroOuterClass.Livros.Builder.class);
      }

      // Construct using LivroOuterClass.Livros.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLivrosFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (livrosBuilder_ == null) {
          livros_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          livrosBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LivroOuterClass.internal_static_Livros_descriptor;
      }

      @java.lang.Override
      public LivroOuterClass.Livros getDefaultInstanceForType() {
        return LivroOuterClass.Livros.getDefaultInstance();
      }

      @java.lang.Override
      public LivroOuterClass.Livros build() {
        LivroOuterClass.Livros result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public LivroOuterClass.Livros buildPartial() {
        LivroOuterClass.Livros result = new LivroOuterClass.Livros(this);
        int from_bitField0_ = bitField0_;
        if (livrosBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            livros_ = java.util.Collections.unmodifiableList(livros_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.livros_ = livros_;
        } else {
          result.livros_ = livrosBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LivroOuterClass.Livros) {
          return mergeFrom((LivroOuterClass.Livros)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LivroOuterClass.Livros other) {
        if (other == LivroOuterClass.Livros.getDefaultInstance()) return this;
        if (livrosBuilder_ == null) {
          if (!other.livros_.isEmpty()) {
            if (livros_.isEmpty()) {
              livros_ = other.livros_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLivrosIsMutable();
              livros_.addAll(other.livros_);
            }
            onChanged();
          }
        } else {
          if (!other.livros_.isEmpty()) {
            if (livrosBuilder_.isEmpty()) {
              livrosBuilder_.dispose();
              livrosBuilder_ = null;
              livros_ = other.livros_;
              bitField0_ = (bitField0_ & ~0x00000001);
              livrosBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLivrosFieldBuilder() : null;
            } else {
              livrosBuilder_.addAllMessages(other.livros_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getLivrosCount(); i++) {
          if (!getLivros(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LivroOuterClass.Livros parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LivroOuterClass.Livros) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<LivroOuterClass.Livro> livros_ =
        java.util.Collections.emptyList();
      private void ensureLivrosIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          livros_ = new java.util.ArrayList<LivroOuterClass.Livro>(livros_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          LivroOuterClass.Livro, LivroOuterClass.Livro.Builder, LivroOuterClass.LivroOrBuilder> livrosBuilder_;

      /**
       * <code>repeated .Livro livros = 1;</code>
       */
      public java.util.List<LivroOuterClass.Livro> getLivrosList() {
        if (livrosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(livros_);
        } else {
          return livrosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Livro livros = 1;</code>
       */
      public int getLivrosCount() {
        if (livrosBuilder_ == null) {
          return livros_.size();
        } else {
          return livrosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Livro livros = 1;</code>
       */
      public LivroOuterClass.Livro getLivros(int index) {
        if (livrosBuilder_ == null) {
          return livros_.get(index);
        } else {
          return livrosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Livro livros = 1;</code>
       */
      public Builder setLivros(
          int index, LivroOuterClass.Livro value) {
        if (livrosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLivrosIsMutable();
          livros_.set(index, value);
          onChanged();
        } else {
          livrosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Livro livros = 1;</code>
       */
      public Builder setLivros(
          int index, LivroOuterClass.Livro.Builder builderForValue) {
        if (livrosBuilder_ == null) {
          ensureLivrosIsMutable();
          livros_.set(index, builderForValue.build());
          onChanged();
        } else {
          livrosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Livro livros = 1;</code>
       */
      public Builder addLivros(LivroOuterClass.Livro value) {
        if (livrosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLivrosIsMutable();
          livros_.add(value);
          onChanged();
        } else {
          livrosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Livro livros = 1;</code>
       */
      public Builder addLivros(
          int index, LivroOuterClass.Livro value) {
        if (livrosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLivrosIsMutable();
          livros_.add(index, value);
          onChanged();
        } else {
          livrosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Livro livros = 1;</code>
       */
      public Builder addLivros(
          LivroOuterClass.Livro.Builder builderForValue) {
        if (livrosBuilder_ == null) {
          ensureLivrosIsMutable();
          livros_.add(builderForValue.build());
          onChanged();
        } else {
          livrosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Livro livros = 1;</code>
       */
      public Builder addLivros(
          int index, LivroOuterClass.Livro.Builder builderForValue) {
        if (livrosBuilder_ == null) {
          ensureLivrosIsMutable();
          livros_.add(index, builderForValue.build());
          onChanged();
        } else {
          livrosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Livro livros = 1;</code>
       */
      public Builder addAllLivros(
          java.lang.Iterable<? extends LivroOuterClass.Livro> values) {
        if (livrosBuilder_ == null) {
          ensureLivrosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, livros_);
          onChanged();
        } else {
          livrosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Livro livros = 1;</code>
       */
      public Builder clearLivros() {
        if (livrosBuilder_ == null) {
          livros_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          livrosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Livro livros = 1;</code>
       */
      public Builder removeLivros(int index) {
        if (livrosBuilder_ == null) {
          ensureLivrosIsMutable();
          livros_.remove(index);
          onChanged();
        } else {
          livrosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Livro livros = 1;</code>
       */
      public LivroOuterClass.Livro.Builder getLivrosBuilder(
          int index) {
        return getLivrosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Livro livros = 1;</code>
       */
      public LivroOuterClass.LivroOrBuilder getLivrosOrBuilder(
          int index) {
        if (livrosBuilder_ == null) {
          return livros_.get(index);  } else {
          return livrosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Livro livros = 1;</code>
       */
      public java.util.List<? extends LivroOuterClass.LivroOrBuilder> 
           getLivrosOrBuilderList() {
        if (livrosBuilder_ != null) {
          return livrosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(livros_);
        }
      }
      /**
       * <code>repeated .Livro livros = 1;</code>
       */
      public LivroOuterClass.Livro.Builder addLivrosBuilder() {
        return getLivrosFieldBuilder().addBuilder(
            LivroOuterClass.Livro.getDefaultInstance());
      }
      /**
       * <code>repeated .Livro livros = 1;</code>
       */
      public LivroOuterClass.Livro.Builder addLivrosBuilder(
          int index) {
        return getLivrosFieldBuilder().addBuilder(
            index, LivroOuterClass.Livro.getDefaultInstance());
      }
      /**
       * <code>repeated .Livro livros = 1;</code>
       */
      public java.util.List<LivroOuterClass.Livro.Builder> 
           getLivrosBuilderList() {
        return getLivrosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          LivroOuterClass.Livro, LivroOuterClass.Livro.Builder, LivroOuterClass.LivroOrBuilder> 
          getLivrosFieldBuilder() {
        if (livrosBuilder_ == null) {
          livrosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              LivroOuterClass.Livro, LivroOuterClass.Livro.Builder, LivroOuterClass.LivroOrBuilder>(
                  livros_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          livros_ = null;
        }
        return livrosBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Livros)
    }

    // @@protoc_insertion_point(class_scope:Livros)
    private static final LivroOuterClass.Livros DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LivroOuterClass.Livros();
    }

    public static LivroOuterClass.Livros getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Livros>
        PARSER = new com.google.protobuf.AbstractParser<Livros>() {
      @java.lang.Override
      public Livros parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Livros(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Livros> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Livros> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public LivroOuterClass.Livros getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Livro_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Livro_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Livros_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Livros_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013livro.proto\"`\n\005Livro\022\n\n\002id\030\001 \002(\005\022\016\n\006ti" +
      "tulo\030\002 \002(\t\022\r\n\005autor\030\003 \002(\t\022\013\n\003ano\030\004 \002(\005\022\017" +
      "\n\007editora\030\005 \002(\t\022\016\n\006genero\030\006 \002(\t\" \n\006Livro" +
      "s\022\026\n\006livros\030\001 \003(\0132\006.Livro"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Livro_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Livro_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Livro_descriptor,
        new java.lang.String[] { "Id", "Titulo", "Autor", "Ano", "Editora", "Genero", });
    internal_static_Livros_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Livros_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Livros_descriptor,
        new java.lang.String[] { "Livros", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
